use std::collections::BTreeMap;

use crate::engine::config::{AgentConfig, ApiEndpoint, ContainerConfig};
use crate::engine::types::AgentType;
use crate::telemetry::config::TelemetryConfig;

/// YAML config file structure — maps directly to the `ash.yml` format.
#[derive(Debug, Clone, serde::Deserialize)]
struct ConfigFile {
    #[serde(default)]
    agents: BTreeMap<String, AgentDef>,
    #[serde(default)]
    telemetry: Option<TelemetryConfig>,
}

/// A single agent definition in the config YAML.
#[derive(Debug, Clone, serde::Deserialize)]
struct AgentDef {
    #[serde(rename = "type", default)]
    agent_type: Option<String>,
    driver: Option<String>,
    cmd: Option<String>,
    args: Option<Vec<String>>,
    model_flag: Option<String>,
    session_flag: Option<String>,
    message_flag: Option<String>,
    stdin_prompt: Option<bool>,
    yes_flag: Option<String>,
}

fn merge_into_config(name: &str, def: AgentDef) -> AgentConfig {
    let agent_type = match def.agent_type.as_deref() {
        Some("api") => AgentType::Api,
        Some("container") => AgentType::Container,
        Some("browser") => AgentType::Browser,
        _ => AgentType::LocalCli,
    };
    let args = def.args.unwrap_or_default();

    let has_driver = def.driver.is_some() && agent_type == AgentType::LocalCli;
    let cmd = if has_driver {
        def.cmd.unwrap_or_default()
    } else {
        def.cmd.unwrap_or_default()
    };

    AgentConfig {
        name: name.to_string(),
        agent_type,
        driver: def.driver,
        cmd,
        args,
        model_flag: def.model_flag,
        session_flag: def.session_flag,
        message_flag: def.message_flag,
        stdin_prompt: def.stdin_prompt.unwrap_or(false),
        yes_flag: def.yes_flag,
        base_url: String::new(),
        auth: None,
        endpoint: ApiEndpoint {
            method: String::new(),
            path: String::new(),
        },
        container: ContainerConfig {
            runtime: String::new(),
            image: String::new(),
            mode: String::new(),
            volumes: Vec::new(),
        },
    }
}

/// Parse the config file and return configured agents and optional telemetry config.
pub fn read_config(path: &str) -> Result<(Vec<AgentConfig>, Option<TelemetryConfig>), String> {
    let content =
        std::fs::read_to_string(path).map_err(|e| format!("failed to read {}: {}", path, e))?;

    if content.trim().is_empty() {
        return Ok((Vec::new(), None));
    }

    let config: ConfigFile =
        serde_yaml::from_str(&content).map_err(|e| format!("failed to parse {}: {}", path, e))?;

    let agents = config
        .agents
        .into_iter()
        .map(|(name, def)| merge_into_config(&name, def))
        .collect();

    Ok((agents, config.telemetry))
}

/// Write the config file with agents and optional telemetry config.
pub fn write_config(
    path: &str,
    agents: &[AgentConfig],
    telemetry: Option<&TelemetryConfig>,
    force: bool,
) -> Result<(), String> {
    let p = std::path::Path::new(path);
    if p.exists() && !force {
        return Err(format!("{} already exists. Use --force to overwrite.", path));
    }

    let yaml = generate_yaml(agents, telemetry);
    std::fs::write(path, &yaml).map_err(|e| format!("failed to write {}: {}", path, e))
}

fn generate_yaml(agents: &[AgentConfig], telemetry: Option<&TelemetryConfig>) -> String {
    let mut y = String::from("# Generated by ash\n");
    header_comment(&mut y, agents, telemetry);

    if !agents.is_empty() {
        y.push_str("agents:\n");
        for agent in agents {
            y.push_str(&format!("  {}:\n", agent.name));
            y.push_str(&yaml_line("type", agent_type_str(&agent.agent_type)));
            if let Some(ref d) = agent.driver {
                y.push_str(&yaml_line("driver", d));
            }
            if !agent.cmd.is_empty() {
                y.push_str(&yaml_line("cmd", &agent.cmd));
            }
            if !agent.args.is_empty() {
                y.push_str(&yaml_line_args("args", &agent.args));
            }
            if let Some(ref f) = agent.model_flag {
                y.push_str(&yaml_line_opt("model_flag", Some(f)));
            }
            if let Some(ref f) = agent.session_flag {
                y.push_str(&yaml_line_opt("session_flag", Some(f)));
            }
            if let Some(ref f) = agent.message_flag {
                y.push_str(&yaml_line_opt("message_flag", Some(f)));
            }
            y.push_str(&yaml_line_bool("stdin_prompt", agent.stdin_prompt));
            if let Some(ref f) = agent.yes_flag {
                y.push_str(&yaml_line_opt("yes_flag", Some(f)));
            }
        }
    }

    if let Some(tc) = telemetry {
        y.push_str("telemetry:\n");
        if let Some(ref filter) = tc.filter {
            y.push_str(&yaml_line("  filter", filter));
        }
        if let Some(ref file) = tc.file {
            y.push_str("  file:\n");
            y.push_str(&yaml_line("    path", &file.path));
            if file.max_size_mb != 100 {
                y.push_str(&yaml_line("    max_size_mb", &file.max_size_mb.to_string()));
            }
            if file.max_files != 7 {
                y.push_str(&yaml_line("    max_files", &file.max_files.to_string()));
            }
        }
    }

    y
}

fn header_comment(y: &mut String, agents: &[AgentConfig], _telemetry: Option<&TelemetryConfig>) {
    if agents.is_empty() && _telemetry.is_none() {
        y.push_str("# No configuration\n");
    }
}

fn agent_type_str(t: &AgentType) -> &'static str {
    match t {
        AgentType::LocalCli => "local-cli",
        AgentType::Api => "api",
        AgentType::Container => "container",
        AgentType::Browser => "browser",
    }
}

fn yaml_line(key: &str, value: &str) -> String {
    format!("    {}: {}\n", key, value)
}

fn yaml_line_opt(key: &str, value: Option<&str>) -> String {
    match value {
        Some(v) => format!("    {}: {}\n", key, v),
        None => String::new(),
    }
}

fn yaml_line_bool(key: &str, value: bool) -> String {
    format!("    {}: {}\n", key, value)
}

fn yaml_line_args(key: &str, args: &[String]) -> String {
    let items: Vec<String> = args.iter().map(|a| format!("      - {}", a)).collect();
    format!("    {}:\n{}\n", key, items.join("\n"))
}

#[cfg(test)]
mod tests {
    use super::*;

    static COUNTER: std::sync::atomic::AtomicUsize = std::sync::atomic::AtomicUsize::new(0);

    fn write_tmp_yaml(content: &str) -> std::path::PathBuf {
        let id = COUNTER.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
        let path = std::env::temp_dir()
            .join(format!("ash-config-test-{}-{}", std::process::id(), id));
        std::fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn test_read_config_new_format() {
        let yaml = r#"# Generated by ash
agents:
  opencode:
    type: local-cli
    cmd: opencode
    args: ["run"]
    model_flag: --model
    session_flag: --continue
    stdin_prompt: false
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].name, "opencode");
        assert_eq!(agents[0].cmd, "opencode");
        assert_eq!(agents[0].args, vec!["run"]);
        assert_eq!(agents[0].model_flag.as_deref(), Some("--model"));
        assert_eq!(agents[0].session_flag.as_deref(), Some("--continue"));
        assert!(agents[0].message_flag.is_none());
        assert_eq!(agents[0].stdin_prompt, false);
        assert!(agents[0].driver.is_none());
    }

    #[test]
    fn test_read_config_old_format() {
        let yaml = r#"agents:
  opencode:
    type: local-cli
    driver: opencode
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].name, "opencode");
        assert_eq!(agents[0].driver.as_deref(), Some("opencode"));
    }

    #[test]
    fn test_read_config_custom_agent() {
        let yaml = r#"agents:
  copilot:
    type: local-cli
    cmd: gh
    args: ["copilot", "suggest"]
    model_flag: --model
    message_flag: --prompt
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].name, "copilot");
        assert_eq!(agents[0].cmd, "gh");
        assert_eq!(agents[0].args, vec!["copilot", "suggest"]);
        assert_eq!(agents[0].model_flag.as_deref(), Some("--model"));
        assert_eq!(agents[0].message_flag.as_deref(), Some("--prompt"));
        assert!(agents[0].session_flag.is_none());
    }

    #[test]
    fn test_read_config_multiple_agents() {
        let yaml = r#"agents:
  opencode:
    type: local-cli
    cmd: opencode
  aider:
    type: local-cli
    cmd: aider
    message_flag: --msg
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 2);
        assert_eq!(agents[0].name, "aider");
        assert_eq!(agents[0].message_flag.as_deref(), Some("--msg"));
        assert_eq!(agents[1].name, "opencode");
    }

    #[test]
    fn test_read_config_empty_file() {
        let path = write_tmp_yaml("");
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert!(agents.is_empty());
    }

    #[test]
    fn test_read_config_no_agents_key() {
        let yaml = "# just a comment\nsome_other_key: value\n";
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert!(agents.is_empty());
    }

    #[test]
    fn test_read_config_mixed_old_and_new() {
        let yaml = r#"agents:
  test-agent:
    type: local-cli
    driver: opencode
    cmd: custom-bin
    model_flag: --model
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].driver.as_deref(), Some("opencode"));
        assert_eq!(agents[0].cmd, "custom-bin");
        assert_eq!(agents[0].model_flag.as_deref(), Some("--model"));
    }

    #[test]
    fn test_read_config_with_yes_flag() {
        let yaml = r#"agents:
  codex:
    type: local-cli
    cmd: codex
    args: ["run"]
    yes_flag: --yolo
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, _) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].name, "codex");
        assert_eq!(agents[0].yes_flag.as_deref(), Some("--yolo"));
    }

    #[test]
    fn test_read_config_with_telemetry() {
        let yaml = r#"agents:
  echo:
    type: local-cli
    driver: echo
telemetry:
  file:
    path: /tmp/ash-telemetry.jsonl
"#;
        let path = write_tmp_yaml(yaml);
        let (agents, telemetry) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(agents.len(), 1);
        assert_eq!(agents[0].name, "echo");

        let tc = telemetry.expect("telemetry config should be present");
        let file = tc.file.expect("file adapter should be present");
        assert_eq!(file.path, "/tmp/ash-telemetry.jsonl");
    }

    #[test]
    fn test_write_and_read_roundtrip() {
        let agents = vec![
            AgentConfig {
                name: "test-agent".into(),
                agent_type: AgentType::LocalCli,
                driver: Some("echo".into()),
                cmd: String::new(),
                args: vec![],
                model_flag: Some("--model".into()),
                session_flag: None,
                message_flag: None,
                stdin_prompt: false,
                yes_flag: None,
                base_url: String::new(),
                auth: None,
                endpoint: ApiEndpoint { method: String::new(), path: String::new() },
                container: ContainerConfig { runtime: String::new(), image: String::new(), mode: String::new(), volumes: vec![] },
            },
        ];
        let path = write_tmp_yaml("");
        // Remove the empty file we just created
        let _ = std::fs::remove_file(&path);

        write_config(path.to_str().unwrap(), &agents, None, false).unwrap();
        let (read_back, telemetry) = read_config(path.to_str().unwrap()).unwrap();
        std::fs::remove_file(&path).ok();
        assert_eq!(read_back.len(), 1);
        assert_eq!(read_back[0].name, "test-agent");
        assert_eq!(read_back[0].driver.as_deref(), Some("echo"));
        assert!(telemetry.is_none());
    }
}
