use std::process::Command;

use super::config::{AgentConfig, ApiEndpoint, ContainerConfig};
use super::from_config;
use super::register;
use super::types::AgentType;

struct DriverInfo {
    pub agent_name: &'static str,
    pub binary_name: &'static str,
    pub driver_name: &'static str,
    pub install_hint: &'static str,
}

const KNOWN_DRIVERS: &[DriverInfo] = &[
    DriverInfo {
        agent_name: "echo",
        binary_name: "echo",
        driver_name: "echo",
        install_hint: "",
    },
    DriverInfo {
        agent_name: "opencode",
        binary_name: "opencode",
        driver_name: "opencode",
        install_hint: "npm i -g @anomalyco/opencode",
    },
    DriverInfo {
        agent_name: "claude-code",
        binary_name: "claude",
        driver_name: "claude-code",
        install_hint: "npm i -g @anthropic-ai/claude-code",
    },
    DriverInfo {
        agent_name: "aider",
        binary_name: "aider",
        driver_name: "aider",
        install_hint: "pip install aider-chat",
    },
];

#[derive(Debug, Clone)]
pub struct DiscoveredAgent {
    pub name: String,
    pub driver: String,
    pub path: String,
    pub version: Option<String>,
    pub supports_model: bool,
    pub supports_session: bool,
    pub found: bool,
    pub install_hint: String,
}

#[derive(Debug, Clone)]
pub struct DiscoveryResult {
    pub agents: Vec<DiscoveredAgent>,
}

fn find_binary(name: &str) -> Option<String> {
    if let Ok(output) = Command::new("which").arg(name).output() {
        if output.status.success() {
            let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !path.is_empty() {
                return Some(path);
            }
        }
    }
    None
}

fn probe_version(binary: &str) -> Option<String> {
    let output = Command::new("timeout")
        .args(["5", binary, "--version"])
        .output();
    if let Ok(output) = output {
        if output.status.success() {
            let version = String::from_utf8_lossy(&output.stdout).trim().to_string();
            if !version.is_empty() {
                return Some(version.lines().next().unwrap_or("").to_string());
            }
        }
    }
    None
}

fn probe_capabilities(binary: &str) -> (bool, bool) {
    let mut supports_model = false;
    let mut supports_session = false;

    let output = Command::new("timeout")
        .args(["5", binary, "--help"])
        .output();

    if let Ok(output) = output {
        let stdout = String::from_utf8_lossy(&output.stdout);
        let stderr = String::from_utf8_lossy(&output.stderr);
        let combined = format!("{}\n{}", stdout, stderr);

        supports_model = combined.contains("--model");
        supports_session =
            combined.contains("--continue") || combined.contains("--restore-chat-history");
    }

    (supports_model, supports_session)
}

pub fn discover() -> DiscoveryResult {
    let mut agents = Vec::new();

    for info in KNOWN_DRIVERS {
        let found_path = find_binary(info.binary_name);

        let (version, supports_model, supports_session) = if found_path.is_some() {
            let v = probe_version(info.binary_name);
            let (m, s) = probe_capabilities(info.binary_name);
            (v, m, s)
        } else {
            (None, false, false)
        };

        let found = found_path.is_some() || info.agent_name == "echo";

        let path = found_path.unwrap_or_else(|| {
            if info.agent_name == "echo" {
                "shell builtin".to_string()
            } else {
                String::new()
            }
        });

        agents.push(DiscoveredAgent {
            name: info.agent_name.to_string(),
            driver: info.driver_name.to_string(),
            path,
            version,
            supports_model,
            supports_session,
            found,
            install_hint: info.install_hint.to_string(),
        });
    }

    DiscoveryResult { agents }
}

pub fn generate_yaml(result: &DiscoveryResult) -> String {
    let mut yaml = String::from("# Generated by `ash discover --write`\nagents:\n");

    let found: Vec<&DiscoveredAgent> = result
        .agents
        .iter()
        .filter(|a| a.found && a.name != "echo")
        .collect();

    if found.is_empty() {
        yaml.push_str("  # No agents discovered\n");
        return yaml;
    }

    for agent in &found {
        yaml.push_str(&format!(
            "  {}:\n    type: local-cli\n    driver: {}\n",
            agent.name, agent.driver
        ));
    }

    yaml
}

pub fn write_config(path: &str, result: &DiscoveryResult, force: bool) -> Result<(), String> {
    let p = std::path::Path::new(path);
    if p.exists() && !force {
        return Err(format!(
            "{} already exists. Use --force to overwrite.",
            path
        ));
    }

    let has_found = result.agents.iter().any(|a| a.found && a.name != "echo");
    if !has_found {
        return Err("no agents found to write to config".to_string());
    }

    let yaml = generate_yaml(result);
    std::fs::write(path, &yaml).map_err(|e| format!("failed to write {}: {}", path, e))
}

pub fn print_discovery(result: &DiscoveryResult) {
    let found: Vec<&DiscoveredAgent> = result.agents.iter().filter(|a| a.found).collect();
    let not_found: Vec<&DiscoveredAgent> = result.agents.iter().filter(|a| !a.found).collect();
    let has_ai_agents = found.iter().any(|a| a.name != "echo");

    if !has_ai_agents && not_found.is_empty() {
        println!("No agents found. Install one: npm i -g @anthropic-ai/claude-code");
        return;
    }

    for agent in &found {
        if agent.name == "echo" {
            continue;
        }
        print!("  {}  {:28}", '\u{2713}', agent.name);
        print!("  {}", agent.path);
        if let Some(ref v) = agent.version {
            print!("  ({})", v);
        }
        println!();
        if agent.supports_model || agent.supports_session {
            print!("      capabilities:");
            if agent.supports_model {
                print!(" model");
            }
            if agent.supports_session {
                print!(" session");
            }
            println!();
        }
    }

    if !not_found.is_empty() {
        if found.iter().any(|a| a.name != "echo") {
            println!();
        }
        for agent in &not_found {
            println!("  {}  {:28}  not found", '\u{2717}', agent.name);
            if !agent.install_hint.is_empty() {
                println!("      install: {}", agent.install_hint);
            }
        }
    }
}

pub fn discovery_summary(result: &DiscoveryResult) -> String {
    let found: Vec<&DiscoveredAgent> = result.agents.iter().filter(|a| a.found).collect();
    let names: Vec<&str> = found.iter().map(|a| a.name.as_str()).collect();

    if names.is_empty() {
        "No agents found. Install one: npm i -g @anthropic-ai/claude-code".to_string()
    } else {
        format!(
            "Found: {}. Run `ash discover` for details.",
            names.join(", ")
        )
    }
}

pub fn discover_and_register() -> DiscoveryResult {
    let result = discover();

    for agent in &result.agents {
        if !agent.found {
            continue;
        }

        let config = AgentConfig {
            name: agent.name.clone(),
            agent_type: AgentType::LocalCli,
            driver: Some(agent.driver.clone()),
            cmd: String::new(),
            args: Vec::new(),
            base_url: String::new(),
            auth: None,
            endpoint: ApiEndpoint {
                method: String::new(),
                path: String::new(),
            },
            container: ContainerConfig {
                runtime: String::new(),
                image: String::new(),
                mode: String::new(),
                volumes: Vec::new(),
            },
        };

        let adapter = from_config(&config);
        register(&agent.name, adapter);
    }

    result
}
